[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "HuKyMocun77xXMWV5JQ1G1iDPSHSrGJo4kDqzNvz8nnX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/i/.config/solana/id.json"

[scripts]
#test = "yarn run mocha -t 1000000 tests/"
test = "node tests/myepicproject.js"
